### ISSUE TITLE
Feature: User can check an email for the breach

### ISSUE THREAD

**Issue by bhaisingh** [bhaisingh/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User will be able to provide an email address and check if it was part of data breach

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Create a responsive form that allows users to enter an email address and check if the email address is part of data breach.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/20628519/126051698-912aed39-1dbd-4abf-afc9-e47c920a1437.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a header area with the option "Search Email Breach".
- [x] Add a validation form for entering the email address.
   - [x] Make the email address field required.
   - [x] Validate if the email is of correct format.
 - [x] Listen for `'submit'` events on the validation form and:
   - [x] make an API call to the "breachedaccount" service.
   - [x] Check for response code of "200". 
   - [x] Build a error handling for all othe response code , 400, 401, 403 etc.
   - [x] Display in ordered list the site from where email was breached and details of the breach.
   - [ ] Reset the form inputs.
- [ ]  Create a footer with "facebook" and "instagram" icon.
- [ ] Ensure that the form looks nice on both mobile-sized and desktop-sized screens.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.

**Comment by bhaisingh** [comment]
Completed Issue-1 search breached email
