### ISSUE TITLE
Feature: User can check a password  as part of data breach.

### ISSUE THREAD

**Issue by bhaisingh** [bhaisingh/ajax-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User will be able to check if a password was exposed as part of data breach.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Create a responsive form that allows users to enter a password and check if the password was exposed as part of data breach.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/20628519/126077231-40c80221-3cc4-4e5b-bf20-73ebc46820d1.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a header area with the option "Search Password Breach".
- [x]  Add a validation form for entering the password.
   - [x] The password is not sent as open text across the internet. 
   - [x] A SHA1 hash needs to be created of the typed password.
   - [x] Only the First 5 SHA1 hash character is sent with the API call.
   - [x] Check for response code of "200".
   - [x] Build a error handling for all other response code , 400, 401, 403 etc.
   - [x] For OK response code , loop through all the returned hash with the password entered hash.
   - [x] If the password hash matches  , display message "You have been breached" 
   - [x] Show the "Generate complex password"  link.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.

**Comment by bhaisingh** [comment]
Completed Issue-2 check if password is part of  previous data breach.
