### ISSUE TITLE
Feature: User can generate a new complex password

### ISSUE THREAD

**Issue by bhaisingh** [bhaisingh/ajax-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can generate a new complex password by defining the complexity length.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Create a responsive form that allows users to enter the length of the complex password and generate a password with Letter, number and special character.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/20628519/126078219-8bc6e26f-e29f-4daa-be23-d2c4513a57ad.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add another option in the header area "Generate complex Password".
- [x] Also make the link visible when the password validation is returned as compromised.
- [x] When the user clicks the link show a text area to enter the length of the password.
   - [x] Validate the length is greater than 12.
   - [x] call the "herokaupp" API service with the length parameter 
   - [x] Check for response code of "200".
   - [x] build error handling for all other responses, 400, 401, 403 etc.
- [x] Display the returned complex password in a text box with an option to copy the text to the clipboard.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.

**Comment by bhaisingh** [comment]
Completed issue-3 User can generate multiple password type
