### ISSUE TITLE
Feature: User can see if a site /domain has been previously breached.

### ISSUE THREAD

**Issue by bhaisingh** [bhaisingh/ajax-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Create a responsive form that allows users to enter a domain address and check if the domain was part of any data breach.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/20628519/126080323-9c219809-1a68-4af2-a297-9a9095a25b2a.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a drop down to choose the search criteria "Email" , "Password", "Site/Domain"
- [x] Validate the domain formatting 
   - [x] The name should consist of .com,  .net , .org etc.
- [x] Use the "breachedaccount" API in conjunction with the  site to check if the email was part of a specific site breach.
- [x] check if the response is not breached , show message "Lucky you - Site is not part of breach".
- [x] if the response is breached , display the link to generate complex password.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.

**Comment by bhaisingh** [comment]
Completed Issue-4 User can search specific site breach
