### ISSUE TITLE
Feature: User can pull All sites which has been breached.

### ISSUE THREAD

**Issue by bhaisingh** [bhaisingh/ajax-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can  see all the sites which has been  breached in past 2 years.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Create a responsive form that allows users to see all the websites which has been breached.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/20628519/126083692-5df94844-b0ee-43cf-b322-c278b485e17c.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a drop down to choose the search criteria "All Sites". 
- [x] Change the button caption to say "Show all Sites".
- [x] Use the "breaches" API module to retrieve the information. 
- [x] The response is shown in tabular format with the icon of the website and the details of the breach
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.

**Comment by bhaisingh** [comment]
Completed issue-5 display all breach sites
